apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-mysql-configmap
data:
  dbName: auth_service

## Init database script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-mysql-initdb
data:
  init.sql: |
    USE auth_service;
    CREATE TABLE IF NOT EXISTS auth (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL
    );
