apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: class-management-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-management-auth-service
  template:
    metadata:
      labels:
        app: class-management-auth-service
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 auth-service-mysql 3306; do echo "Waiting for MySQL"; sleep 5; done']
      containers:
        - name: class-management-auth-service-container
          image: th1enlm02/class-management-auth-service:latest
          ports:
            - containerPort: 3077
          env:
            - name: BASE_URL_FE
              value: "http://frontend-service:3000"
            - name: AUTH_SERVICE_PORT
              value: "3077"
            - name: AUTH_SERVICE_HOST
              value: auth-service-mysql
            - name: AUTH_SERVICE_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: auth-mysql-configmap
                  key: dbName
            - name: AUTH_SERVICE_USER
              value: "root"
            - name: AUTH_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mysql-secret
                  key: rootPassword

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql-deployment
  labels:
    app: auth-service-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-service-mysql
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 auth-service-mysql-container 3306; do echo "Waiting for MySQL"; sleep 5; done']
      containers:
        - name: auth-service-mysql-container
          image: mysql:8.0
          # resources:
          #   requests:
          #     cpu: 5m
          #     memory: 50Mi
          #   limits:
          #     cpu: 100m
          #     memory: 1Gi
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_HOST
              value: auth-service-mysql
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: auth-mysql-configmap
                  key: dbName
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: auth-mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mysql-secret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mysql-secret
                  key: rootPassword
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - mysqladmin
              - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: auth-service-mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: auth-service-mysql-data
          persistentVolumeClaim:
            claimName: auth-mysql-pvc
        - name: init-sql
          configMap:
            name: auth-mysql-initdb
            items:
              - key: init.sql
                path: init.sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment-phpmyadmin
  labels:
    app: auth-service-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-phpmyadmin
  template:
    metadata:
      labels:
        app: auth-service-phpmyadmin
    spec:
      containers:
        - name: auth-phpmyadmin-container
          image: phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: auth-service-mysql
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mysql-secret
                  key: rootPassword
