apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: class-management-auth-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 3077
      targetPort: 3077
      nodePort: 30377

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-mysql
spec:
  selector:
    app: auth-service-mysql
  ports:
    - port: 3305
      targetPort: 3306
  clusterIP: None
  
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-phpmyadmin
spec:
  selector:
    app: auth-service-phpmyadmin
  type: NodePort
  ports:
    - protocol: TCP
      port: 79
      targetPort: 80
      nodePort: 30079
