apiVersion: v1
kind: Service
metadata:
  name: class-service
spec:
  selector:
    app: class-management-class-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30800

---
apiVersion: v1
kind: Service
metadata:
  name: class-service-postgresql
spec:
  selector:
    app: class-service-postgresql
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: class-service-pgadmin
spec:
  selector:
    app: class-service-pgadmin
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
      nodePort: 30882