apiVersion: v1
kind: PersistentVolume
metadata:
  name: student-service-mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/student-service-mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-service-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
