apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-deployment
  labels:
    app: class-management-lecturer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-management-lecturer-service
  template:
    metadata:
      labels:
        app: class-management-lecturer-service
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 lecturer-service-mongodb 27017; do echo "Waiting for MongoDB"; sleep 5; done']
      containers:
        - name: class-management-lecturer-service-container
          image: th1enlm02/class-management-lecturer-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: HOST_NAME
              value: root:th1enlm02_root@lecturer-service-mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-mongodb-deployment
  labels:
    app: lecturer-service-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecturer-service-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lecturer-service-mongodb
    spec:
      containers:
        - name: lecturer-service-mongodb-container
          image: mongo:7.0.9
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lecturer-mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lecturer-mongodb-secret
                  key: password
          volumeMounts:
            - name: lecturer-service-mongodb-data
              mountPath: /data/db
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: lecturer-service-mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-mongo-express-deployment
  labels:
    app: lecturer-service-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecturer-service-mongo-express
  template:
    metadata:
      labels:
        app: lecturer-service-mongo-express
    spec:
      containers:
        - name: lecturer-service-mongo-express-container
          image: mongo-express:1-20
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_BASICAUTH
              value: "false"
            - name: ME_CONFIG_MONGODB_SERVER
              value: lecturer-service-mongodb
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://root:th1enlm02_root@lecturer-service-mongodb:27017
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "th1enlm02_root"
