apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-deployment
  labels:
    app: class-management-lecturer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: class-management-lecturer-service
  template:
    metadata:
      labels:
        app: class-management-lecturer-service
    spec:
      containers:
        - name: class-management-lecturer-service-container
          image: th1enlm02/class-management-lecturer-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: HOST_NAME
              value: root:th1enlm02_root@lecturer-service-mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-deployment-mongodb
  labels:
    app: lecturer-service-mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lecturer-service-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lecturer-service-mongodb
    spec:
      containers:
        - name: lecturer-service-mongodb-container
          image: mongo:7.0.9
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lecturer-service-mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lecturer-service-mongodb-secret
                  key: password
          volumeMounts:
            - name: lecturer-service-mongodb-data
              mountPath: /data/db
      volumes:
        - name: lecturer-service-mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-deployment-mongo-express
  labels:
    app: lecturer-mongo-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lecturer-mongo-express
  template:
    metadata:
      labels:
        app: lecturer-mongo-express
    spec:
      containers:
        - name: lecturer-mongo-express-container
          image: mongo-express:1-20
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_BASICAUTH
              value: "false"
            - name: ME_CONFIG_MONGODB_SERVER
              value: lecturer-service-mongodb
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://lecturer-service-mongodb:27017
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: lecturer-service-mongo-express-secret
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: lecturer-service-mongo-express-secret
                  key: password
