apiVersion: v1
kind: Service
metadata:
  name: lecturer-service
spec:
  selector:
    app: class-management-lecturer-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500

---
apiVersion: v1
kind: Service
metadata:
  name: lecturer-service-mongodb
spec:
  selector:
    app: lecturer-service-mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: lecturer-service-mongo-express
spec:
  selector:
    app: lecturer-service-mongo-express
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30881
